# Generated by Django 6.0 on 2026-01-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_games_free', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentoffer',
            old_name='name',
            new_name='title',
        ),
    ]
